// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResolveOps.Persistence;

#nullable disable

namespace ResolveOps.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917142552_AddExceptionPoliciesAndCases")]
    partial class AddExceptionPoliciesAndCases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.ErrorTemplate", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("created_by");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int")
                        .HasColumnName("http_status_code");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("message_template");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("Code");

                    b.ToTable("error_templates", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Exceptions.CaseTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("case_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details_json");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entry_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("TenantId", "CaseId", "CreatedAtUtc")
                        .HasDatabaseName("IX_CaseTimelineEntries_TenantCaseCreatedAt");

                    b.ToTable("case_timeline_entries", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Exceptions.ExceptionCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("case_number");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_at_utc");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("detected_at_utc");

                    b.Property<string>("DispositionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("disposition_code");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("exception_type");

                    b.Property<string>("ExposureCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("exposure_currency");

                    b.Property<decimal>("FinancialExposure")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("financial_exposure");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("OwnerTeamCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("owner_team_code");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("policy_id");

                    b.Property<int>("PolicyVersionNumber")
                        .HasColumnType("int")
                        .HasColumnName("policy_version_number");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("RootCauseCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("root_cause_code");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("severity");

                    b.Property<int?>("SeverityScore")
                        .HasColumnType("int")
                        .HasColumnName("severity_score");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shipment_id");

                    b.Property<Guid?>("ShipmentLegId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shipment_leg_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaseNumber")
                        .IsUnique()
                        .HasDatabaseName("UIX_ExceptionCases_TenantCaseNumber");

                    b.HasIndex("TenantId", "Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("UIX_ExceptionCases_ActiveFingerprint")
                        .HasFilter("[status] NOT IN ('Closed', 'Cancelled')");

                    b.HasIndex("TenantId", "ShipmentId")
                        .HasDatabaseName("IX_ExceptionCases_TenantShipment");

                    b.HasIndex("TenantId", "Status", "Severity")
                        .HasDatabaseName("IX_ExceptionCases_TenantStatusSeverity");

                    b.ToTable("exception_cases", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Exceptions.ExceptionOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("observed_at_utc");

                    b.Property<string>("OccurrenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("occurrence_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TrackingEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tracking_event_id");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("TenantId", "CaseId")
                        .HasDatabaseName("IX_ExceptionOccurrences_TenantCase");

                    b.ToTable("exception_occurrences", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Exceptions.ExceptionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssignmentDefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assignment_definition_json");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("effective_to_utc");

                    b.Property<Guid?>("EvidencePolicyVersionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("evidence_policy_version_id");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("exception_type");

                    b.Property<string>("PolicyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("policy_key");

                    b.Property<string>("RuleDefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rule_definition_json");

                    b.Property<string>("SeverityDefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("severity_definition_json");

                    b.Property<Guid?>("SlaPolicyVersionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sla_policy_version_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExceptionType", "Status")
                        .HasDatabaseName("IX_ExceptionPolicies_TenantTypeStatus");

                    b.HasIndex("TenantId", "PolicyKey", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UIX_ExceptionPolicies_TenantKeyVersion");

                    b.ToTable("exception_policies", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsSystemAccount")
                        .HasColumnType("bit")
                        .HasColumnName("is_system_account");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[normalized_user_name] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Identity.RefreshTokenSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("CreatedIpHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("created_ip_hash");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("user_agent_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "ExpiresAtUtc");

                    b.HasIndex("UserId", "FamilyId");

                    b.ToTable("refresh_token_sessions", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Identity.UserTenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("roles_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique();

                    b.ToTable("user_tenant_memberships", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Messaging.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Scope")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("scope");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("request_hash");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("int")
                        .HasColumnName("response_status");

                    b.HasKey("TenantId", "Scope", "IdempotencyKey");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Messaging.InboxMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("consumer_name");

                    b.Property<string>("MessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("ResultHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("result_hash");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("ConsumerName", "MessageId");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PartitionKey")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("partition_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("int")
                        .HasColumnName("processing_attempts");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("processing_status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingStatus", "NextAttemptAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("IX_OutboxMessages_StatusNextAttempt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Partners.BusinessCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<int>("WorkingDaysMask")
                        .HasColumnType("int")
                        .HasColumnName("working_days_mask");

                    b.Property<TimeOnly>("WorkingEnd")
                        .HasColumnType("time")
                        .HasColumnName("working_end");

                    b.Property<TimeOnly>("WorkingStart")
                        .HasColumnType("time")
                        .HasColumnName("working_start");

                    b.HasKey("Id");

                    b.ToTable("business_calendars");
                });

            modelBuilder.Entity("ResolveOps.Domain.Partners.BusinessCalendarHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("BusinessCalendarId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_calendar_id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("calendar_id");

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date")
                        .HasColumnName("holiday_date");

                    b.Property<bool>("IsWorkingOverride")
                        .HasColumnType("bit")
                        .HasColumnName("is_working_override");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessCalendarId");

                    b.ToTable("business_calendar_holiday");
                });

            modelBuilder.Entity("ResolveOps.Domain.Partners.Carrier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ClaimSubmissionChannel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_submission_channel");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultTimezone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("default_timezone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("ScacOrExternalCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scac_or_external_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("carriers");
                });

            modelBuilder.Entity("ResolveOps.Domain.Partners.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultTimezone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("default_timezone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("ResolveOps.Domain.Partners.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("ResolveOps.Domain.Shipments.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualDeliveryAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("actual_delivery_at_utc");

                    b.Property<DateTimeOffset?>("ActualPickupAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("actual_pickup_at_utc");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<decimal?>("DeclaredValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("declared_value");

                    b.Property<string>("DeclaredValueCurrency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("declared_value_currency");

                    b.Property<Guid>("DestinationLocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("destination_location_id");

                    b.Property<int?>("ExpectedPackageCount")
                        .HasColumnType("int")
                        .HasColumnName("expected_package_count");

                    b.Property<decimal?>("ExpectedWeight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("expected_weight");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("OriginLocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("origin_location_id");

                    b.Property<DateTimeOffset>("PlannedDeliveryAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("planned_delivery_at_utc");

                    b.Property<DateTimeOffset>("PlannedPickupAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("planned_pickup_at_utc");

                    b.Property<string>("ServiceLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("service_level");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updated_by");

                    b.Property<string>("WeightUnit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("weight_unit");

                    b.HasKey("Id");

                    b.ToTable("shipments");
                });

            modelBuilder.Entity("ResolveOps.Domain.Shipments.ShipmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal>("ExpectedQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("expected_quantity");

                    b.Property<string>("LineReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("line_reference");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("quantity_unit");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sku");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("UnitValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_value");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("shipment_items");
                });

            modelBuilder.Entity("ResolveOps.Domain.Shipments.ShipmentLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualArrivalAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("actual_arrival_at_utc");

                    b.Property<DateTimeOffset?>("ActualDepartureAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("actual_departure_at_utc");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("carrier_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<Guid>("DestinationLocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("destination_location_id");

                    b.Property<Guid>("OriginLocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("origin_location_id");

                    b.Property<DateTimeOffset?>("PlannedArrivalAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("planned_arrival_at_utc");

                    b.Property<DateTimeOffset?>("PlannedDepartureAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("planned_departure_at_utc");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int")
                        .HasColumnName("sequence_number");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tracking_number");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("shipment_legs");
                });

            modelBuilder.Entity("ResolveOps.Domain.Shipments.ShipmentTrackingAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AliasType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alias_type");

                    b.Property<string>("AliasValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alias_value");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("carrier_id");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shipment_id");

                    b.Property<Guid?>("ShipmentLegId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shipment_leg_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("shipment_tracking_aliases");
                });

            modelBuilder.Entity("ResolveOps.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("nchar(3)")
                        .HasColumnName("default_currency");

                    b.Property<string>("DefaultTimezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("default_timezone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Tenancy.TenantSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("settings_json");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("TenantId");

                    b.ToTable("tenant_settings", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Tracking.InboundEventReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("carrier_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("external_event_id");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureDetail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("failure_detail");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("payload_hash");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("processing_status");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_payload");

                    b.Property<string>("RawPayloadUri")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("raw_payload_uri");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at_utc");

                    b.Property<bool?>("SignatureValid")
                        .HasColumnType("bit")
                        .HasColumnName("signature_valid");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source_system");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SourceSystem", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("UIX_InboundEventReceipts_TenantSourceExternalEvent")
                        .HasFilter("[external_event_id] IS NOT NULL");

                    b.ToTable("inbound_event_receipts", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Tracking.QuarantinedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_user_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<Guid>("InboundReceiptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inbound_receipt_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reason_code");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("resolved_at_utc");

                    b.Property<Guid?>("ResolvedShipmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("resolved_shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_QuarantinedEvents_TenantStatusCreated");

                    b.ToTable("quarantined_events", (string)null);
                });

            modelBuilder.Entity("ResolveOps.Domain.Tracking.TrackingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("carrier_id");

                    b.Property<string>("CausationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("causation_id");

                    b.Property<Guid?>("CorrectionOfEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correction_of_event_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("event_code");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("external_event_id");

                    b.Property<Guid>("InboundReceiptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inbound_receipt_id");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("location_text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at_utc");

                    b.Property<int?>("PackageCount")
                        .HasColumnType("int")
                        .HasColumnName("package_count");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at_utc");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shipment_id");

                    b.Property<Guid?>("ShipmentLegId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shipment_leg_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CarrierId", "ExternalEventId")
                        .HasDatabaseName("IX_TrackingEvents_CarrierExternalEvent");

                    b.HasIndex("TenantId", "ShipmentId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("IX_TrackingEvents_ShipmentTimeline");

                    b.ToTable("tracking_events", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ResolveOps.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ResolveOps.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResolveOps.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ResolveOps.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResolveOps.Domain.Exceptions.CaseTimelineEntry", b =>
                {
                    b.HasOne("ResolveOps.Domain.Exceptions.ExceptionCase", null)
                        .WithMany("TimelineEntries")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResolveOps.Domain.Exceptions.ExceptionOccurrence", b =>
                {
                    b.HasOne("ResolveOps.Domain.Exceptions.ExceptionCase", null)
                        .WithMany("Occurrences")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResolveOps.Domain.Partners.BusinessCalendarHoliday", b =>
                {
                    b.HasOne("ResolveOps.Domain.Partners.BusinessCalendar", null)
                        .WithMany("Holidays")
                        .HasForeignKey("BusinessCalendarId");
                });

            modelBuilder.Entity("ResolveOps.Domain.Shipments.ShipmentItem", b =>
                {
                    b.HasOne("ResolveOps.Domain.Shipments.Shipment", null)
                        .WithMany("Items")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResolveOps.Domain.Shipments.ShipmentLeg", b =>
                {
                    b.HasOne("ResolveOps.Domain.Shipments.Shipment", null)
                        .WithMany("Legs")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResolveOps.Domain.Shipments.ShipmentTrackingAlias", b =>
                {
                    b.HasOne("ResolveOps.Domain.Shipments.Shipment", null)
                        .WithMany("TrackingAliases")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResolveOps.Domain.Exceptions.ExceptionCase", b =>
                {
                    b.Navigation("Occurrences");

                    b.Navigation("TimelineEntries");
                });

            modelBuilder.Entity("ResolveOps.Domain.Partners.BusinessCalendar", b =>
                {
                    b.Navigation("Holidays");
                });

            modelBuilder.Entity("ResolveOps.Domain.Shipments.Shipment", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Legs");

                    b.Navigation("TrackingAliases");
                });
#pragma warning restore 612, 618
        }
    }
}
