<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);NU1903;CA1707;CA1861;CA1859;CA1812</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Dapper" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\ResolveOps.Domain\ResolveOps.Domain.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\ResolveOps.Application\ResolveOps.Application.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\ResolveOps.Persistence\ResolveOps.Persistence.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\ResolveOps.Messaging\ResolveOps.Messaging.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\ResolveOps.Observability\ResolveOps.Observability.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\ResolveOps.Security\ResolveOps.Security.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Shipments\ResolveOps.Modules.Shipments.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Tracking\ResolveOps.Modules.Tracking.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Exceptions\ResolveOps.Modules.Exceptions.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Claims\ResolveOps.Modules.Claims.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Documents\ResolveOps.Modules.Documents.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Workflow\ResolveOps.Modules.Workflow.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Reporting\ResolveOps.Modules.Reporting.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Notifications\ResolveOps.Modules.Notifications.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Partners\ResolveOps.Modules.Partners.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Tenancy\ResolveOps.Modules.Tenancy.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Identity\ResolveOps.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\ResolveOps.Modules.Integrations\ResolveOps.Modules.Integrations.csproj" />
  </ItemGroup>

</Project>
