<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ResolveOps.Domain\ResolveOps.Domain.csproj" />
    <ProjectReference Include="..\ResolveOps.Persistence\ResolveOps.Persistence.csproj" />
  </ItemGroup>

</Project>
