<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Aspire.StackExchange.Redis" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\ResolveOps.Security\ResolveOps.Security.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\ResolveOps.Persistence\ResolveOps.Persistence.csproj" />
    <ProjectReference Include="..\..\Modules\ResolveOps.Modules.Identity\ResolveOps.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\Modules\ResolveOps.Modules.Tenancy\ResolveOps.Modules.Tenancy.csproj" />
    <ProjectReference Include="..\..\ServiceDefaults\ResolveOps.ServiceDefaults\ResolveOps.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Modules\ResolveOps.Modules.Partners\ResolveOps.Modules.Partners.csproj" />
    <ProjectReference Include="..\..\Modules\ResolveOps.Modules.Shipments\ResolveOps.Modules.Shipments.csproj" />
    <ProjectReference Include="..\..\Modules\ResolveOps.Modules.Integrations\ResolveOps.Modules.Integrations.csproj" />
    <ProjectReference Include="..\..\Modules\ResolveOps.Modules.Tracking\ResolveOps.Modules.Tracking.csproj" />
  </ItemGroup>

</Project>
